development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: capstone_repeat_api_development
      hosts:
        - <%= ENV['MONGO_HOST'] ||= "localhost:27017" %>
      options:
       server_selection_timeout: 5

  options:
test:
  clients:
    default:
      database: capstone_repeat_api_test
      hosts:
        - <%= ENV['MONGO_HOST'] ||= "localhost:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15